-- Ameliorations : remboursement + notification client "commande prete".
-- A coller dans Supabase -> SQL Editor -> Run. (Sans accents : sur pour le collage.)

-- 1) Remboursement : marque une commande remboursee
alter table commandes add column if not exists remboursee boolean default false;

-- 2) Notifications client : les appareils abonnes, par numero de commande
create table if not exists push_clients (
  id bigint generated by default as identity primary key,
  numero text not null,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  cree_le timestamptz default now(),
  unique (numero, endpoint)
);
alter table push_clients enable row level security;

-- Le client (non connecte) peut s'abonner ; personne ne peut lire la liste
-- (seule la fonction serveur, avec la cle service, y accede).
create policy "abonnement client" on push_clients for insert with check (true);
create policy "maj abonnement client" on push_clients for update using (true) with check (true);
