-- ============================================================
--  PainPrêt — Schéma de la base de données (Supabase)
--  ------------------------------------------------------------
--  À coller dans : Supabase → SQL Editor → New query → Run
--  Crée les tables produits / commandes / réglages,
--  la fonction "passer_commande" (paiement validé → commande +
--  stock décompté d'un coup, sans risque de survente),
--  et les règles de sécurité.
-- ============================================================

-- ---------- 1. Les produits ----------
create table if not exists produits (
  id bigint generated by default as identity primary key,
  nom text not null,
  categorie text not null default 'pains',
  sous_categorie text,
  prix numeric(6, 2) not null check (prix >= 0),
  description text default '',
  image text, -- URL de la photo (Supabase Storage plus tard)
  emoji text default '🥖',
  ingredients text[] default '{}',
  allergenes text[] default '{}',
  delai_preparation int default 10,
  stock int not null default 0 check (stock >= 0),
  populaire boolean default false,
  nouveau boolean default false,
  cree_le timestamptz default now()
);

-- ---------- 2. Les commandes ----------
create table if not exists commandes (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  client text default '',
  email text default '',
  creneau text not null,
  heure_retrait timestamptz,
  statut text not null default 'a-preparer'
    check (statut in ('a-preparer', 'prete', 'livree')),
  articles jsonb not null, -- [{produitId, nom, quantite, remarque}]
  total numeric(8, 2) not null,
  arrive boolean default false,
  cree_le timestamptz default now()
);

-- ---------- 3. Les réglages de la boutique ----------
create table if not exists reglages (
  id int primary key default 1 check (id = 1), -- une seule ligne
  boutique_fermee boolean default false
);
insert into reglages (id) values (1) on conflict do nothing;

-- ---------- 4. Passer une commande (transaction sûre) ----------
-- Vérifie le stock, le décompte, et crée la commande EN UNE FOIS.
-- Si un produit n'a plus assez de stock, TOUT est annulé.
create or replace function passer_commande(
  p_client text,
  p_email text,
  p_creneau text,
  p_heure_retrait timestamptz,
  p_articles jsonb,
  p_total numeric
) returns commandes
language plpgsql
security definer
as $$
declare
  article jsonb;
  nouvelle commandes;
  v_numero text;
begin
  -- Boutique fermée ? On refuse.
  if (select boutique_fermee from reglages where id = 1) then
    raise exception 'boutique_fermee';
  end if;

  -- Décompte du stock, produit par produit (verrouillé le temps de l'opération)
  for article in select * from jsonb_array_elements(p_articles) loop
    update produits
      set stock = stock - (article ->> 'quantite')::int
      where id = (article ->> 'produitId')::bigint
        and stock >= (article ->> 'quantite')::int;
    if not found then
      raise exception 'stock_insuffisant: %', article ->> 'nom';
    end if;
  end loop;

  -- Numéro lisible : lettre B + 2 chiffres, unique
  v_numero := 'B' || lpad((floor(random() * 90) + 10)::text, 2, '0');
  while exists (select 1 from commandes where numero = v_numero) loop
    v_numero := 'B' || lpad((floor(random() * 90) + 10)::text, 2, '0');
  end loop;

  insert into commandes (numero, client, email, creneau, heure_retrait, articles, total)
    values (v_numero, p_client, p_email, p_creneau, p_heure_retrait, p_articles, p_total)
    returning * into nouvelle;

  return nouvelle;
end;
$$;

-- ---------- 5. Sécurité (Row Level Security) ----------
alter table produits enable row level security;
alter table commandes enable row level security;
alter table reglages enable row level security;

-- Tout le monde peut LIRE les produits et les réglages (le site vitrine)
create policy "produits visibles par tous" on produits for select using (true);
create policy "reglages visibles par tous" on reglages for select using (true);

-- Les clients lisent les commandes (pour suivre la leur par numéro)
create policy "commandes visibles" on commandes for select using (true);
-- Le client peut signaler son arrivée (colonne arrive uniquement, via update simple)
create policy "signaler arrivee" on commandes for update using (true) with check (true);

-- Seul le boulanger CONNECTÉ (compte Supabase Auth) modifie produits et réglages
create policy "boulanger gere produits" on produits
  for all to authenticated using (true) with check (true);
create policy "boulanger gere reglages" on reglages
  for update to authenticated using (true) with check (true);

-- ---------- 6. Temps réel ----------
-- Active les mises à jour instantanées (nouvelle commande → sonnerie boulanger)
alter publication supabase_realtime add table commandes;
alter publication supabase_realtime add table produits;
alter publication supabase_realtime add table reglages;
