-- Phase 2 Stripe : la commande est creee par le webhook (paiement garanti),
-- meme si le client ferme sa page. A coller dans SQL Editor -> Run.

-- Colonne pour relier une commande a sa session de paiement Stripe
alter table commandes add column if not exists stripe_session text;

-- Table tampon : la commande "en attente de paiement" (creee par creer-paiement,
-- transformee en vraie commande par le webhook, puis supprimee).
create table if not exists commandes_en_attente (
  id bigint generated by default as identity primary key,
  client text default '',
  email text default '',
  telephone text default '',
  creneau text not null,
  heure_retrait timestamptz,
  articles jsonb not null,
  total numeric(8, 2) not null,
  cree_le timestamptz default now()
);
alter table commandes_en_attente enable row level security;
-- (aucune policy : seules les fonctions serveur y accedent, via la cle service)

-- passer_commande accepte desormais la session Stripe
drop function if exists passer_commande(text, text, text, text, timestamptz, jsonb, numeric);

create or replace function passer_commande(
  p_client text,
  p_email text,
  p_telephone text,
  p_stripe_session text,
  p_creneau text,
  p_heure_retrait timestamptz,
  p_articles jsonb,
  p_total numeric
) returns commandes
language plpgsql
security definer
as $$
declare
  article jsonb;
  nouvelle commandes;
  v_numero text;
begin
  -- Anti-doublon : si la session a deja cree une commande, on la renvoie
  select * into nouvelle from commandes where stripe_session = p_stripe_session
    and p_stripe_session is not null limit 1;
  if found then return nouvelle; end if;

  for article in select * from jsonb_array_elements(p_articles) loop
    update produits
      set stock = stock - (article ->> 'quantite')::int
      where id = (article ->> 'produitId')::bigint
        and stock >= (article ->> 'quantite')::int;
    if not found then
      raise exception 'stock_insuffisant: %', article ->> 'nom';
    end if;
  end loop;

  v_numero := 'B' || lpad((floor(random() * 90) + 10)::text, 2, '0');
  while exists (select 1 from commandes where numero = v_numero) loop
    v_numero := 'B' || lpad((floor(random() * 90) + 10)::text, 2, '0');
  end loop;

  insert into commandes (numero, client, email, telephone, stripe_session, creneau, heure_retrait, articles, total)
    values (v_numero, p_client, p_email, p_telephone, p_stripe_session, p_creneau, p_heure_retrait, p_articles, p_total)
    returning * into nouvelle;

  return nouvelle;
end;
$$;
